[package]
name = "semiring"
version = "0.1.0"
authors = ["Daniel van Niekerk <dvn.demitasse@gmail.com>"]

[dependencies]
num = "*"

[lib]
name = "semiring"
path = "src/semiring.rs"

[[bin]]
name = "main"
path = "src/main.rs"
